### PR TITLE
Making system tests work on windows

### PR DESCRIPTION
**Pull request by rerpha**
### Issue

?

### Description of work

*Add a description of the work done. The aim is provide information to help the reviewer review the PR efficiently.
See [CONTRIBUTING.MD](CONTRIBUTING.MD) for more information on code standards etc.*

### Nominate for Group Code Review

- [ ] Nominate for code review 

### Reminder

*Changes should be documented in `changes.md`*

### CODE REVIEW

**Comment by mchorazak** [comment]
# [Codecov](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/324?src=pr&el=h1) Report
> Merging [#324](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/324?src=pr&el=desc) into [master](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/commit/782c1ea182996c29e0fc1fb5abf674b956cc262a&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.


```diff
@@           Coverage Diff           @@
##           master     #324   +/-   ##
=======================================
  Coverage   70.52%   70.52%           
=======================================
  Files          98       98           
  Lines        2819     2819           
=======================================
  Hits         1988     1988           
  Misses        831      831           
```

**Comment by rerpha** [comment]
ok, i have spent ages trying to get them to work but the problem seems to be the way docker for windows does not map the ports correctly. caproto is not the issue here, as i cannot do a `caget SIMPLE:DOUBLE` either and therefore the IOC cannot be reached. 

I have tried: 
- explicitly setting ports and exposing them via the docker-compose script 
- switching to hyper-v AND windows containers 
- using a bridge network in the compose script 
- running `docker run -it screamingudder/softioc`

This PR has fixed the line ending problem, so the image can at least now be built on docker for windows, but the tests cannot yet be run.

**Comment by rerpha** [comment]
The same tests are repeatably passing and failing for me currently. 

p: 
test_forwarder_status_shows_added_pvs
test_forwarder_can_handle_rapid_config_updates (surprisingly!)
test_forwarder_sends_fake_pv_updates
test_forwarder_sends_idle_pv_updates

f: the rest

**Comment by rerpha** [comment]
Ok, they are failing on linux now too. I am going to try and get the WSL2 docker engine working today and see if I can run the containers in linux mode to see if i can at least get the IOC working properly on both platforms. 

This requires win10 build 19018

**Comment by rerpha** [comment]
On windows containers: 
- Any containers that expose ports (Zookeeper, Kafka, etc) are disallowed due to hyper-v
- Using network_mode: host causes the containers to halt 

On Linux containers:
- IOC works with port manually exposed and custom network set up 
- Zookeeper works 
- Kafka cannot connect to zookeeper and therefore halts

**Pull request closed without merging**
