### PR TITLE
Dm 1246 fmt update

### PR DESCRIPTION
**Pull request by SkyToGround**
### Issue

DM-1246

### Description of work

* Update the FMT library to the latest available version (5.3).
* Removed old and now useless CMake code.
* Due to linking issues under Windows, switched to using the FMT library as header only
* Updated the Jenkins build images due to issues with older versions of Conan. 
* Fixed Windows compile issues (thanks @mattclarke).

### Nominate for Group Code Review

- [ ] Nominate for code review

### CODE REVIEW

**Comment by SkyToGround** [comment]
@matthew-d-jones @rerpha @mchorazak Having the fmt library as header only solved one compilation issue with Windows but now there is another one. For the life of me I can not understand how my changes results in the error messages that I see. Hence, I leave it to you to figure it out.

**Comment by mattclarke** [comment]
This seems to have fixed it. I think the issue is that WinSock2.h has a very sensitive relationship to other Win32 headers. I suspect moving FMT to header only causes a conflict.
I have hacked a workaround because the relevant code is only used in the CURL reporter which won't be used on Win32 anyway.

**Comment by matthew-d-jones** [comment]
@SkyToGround There should be a "Ready for review" button somewhere to promote this from a draft PR.
I'm just waiting for an email reply from Mark on whether they are using InfluxDB at SINQ, if not we can simply remove the troublesome curl code altogether.

**Comment by SkyToGround** [comment]
@matthew-d-jones Done.

**Comment by dominikwerder** [comment]
Fmt 5 in the forwarder :+1:  great!

**Comment by dominikwerder** [comment]
The failing build looks like a Jenkins issue?

**Comment by SkyToGround** [comment]
Thanks!

**Pull request merged**
