### PR TITLE
Changing Consumer to assign to highest offset on partition rather than lowest. 

### PR DESCRIPTION
**Pull request by rerpha**
### Description of work

The Forwarder was previously assigning to the highest offset on a partition, therefore meaning that if there were already commands on the topic it was assigned to for receiving command messages, it would try and add PVs that might not exist anymore. 

### Issue

DM-1322

### Acceptance Criteria

Changed set_offset call to assign from highest offset on each `RdKafka::TopicPartition.`

### Unit Tests

None modified. 

### Other

None

---

## Code Review (To be filled in by the reviewer only)

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?

---

## Nominate for Group Code Review (Anyone can nominate it)
Indicate if you think the code should be reviewed in a Thursday code review session.

- [ ] Recommend for group code review

Also, nominate it on the code_review Slack channel (does someone want to automate this?).

### CODE REVIEW

**Comment by SkyToGround** [comment]
I would like to point out that the reason that this has to be fixed is due to the seriously silly implementation for receiving commands that is used. The forwarder (and file-writer) should REALLY be moved to using a proper request-response based protocol for commands.

**Comment by mattclarke** [comment]
Is there a JIRA ticket for it?

**Comment by matthew-d-jones** [comment]
> Is there a JIRA ticket for it?

In the branch name and the PR description

**Comment by mattclarke** [comment]
That was a response to Jonas' comment. I can read a PR cheers ;)

**Pull request merged**
