### PR TITLE
Use relative rpaths on all unix platforms

### PR DESCRIPTION
**Pull request by matthew-d-jones**
### Issue

DM-1677

### Description of work

In the `CMakeLists.txt` tell the linker to set relative rpaths.

### Nominate for Group Code Review

- [ ] Nominate for code review

### CODE REVIEW

**Comment by mattclarke** [comment]
On my mac (with clang) I needed to change it to `-rpath,$ORIGIN/../lib`. I.e. replace the equals sign with a comma (I believe that should work on linux too). 

It also didn't like $ORIGIN either, so I did -rpath,'\\\$ORIGIN/../lib' just to get it working (see https://cmake.org/pipermail/cmake/2008-January/019290.html).

It also doesn't understand `--disable-new-dtags`, so I removed that.

Then it built okay ;)

**Comment by matthew-d-jones** [comment]
Thanks @mattclarke, hopefully this now works for everyone?

**Comment by mattclarke** [comment]
What about `RelWithDebInfo` (as mentioned in the other PR), do we want to do this?

**Comment by matthew-d-jones** [comment]
By default I think it drops optimisation level to 2 from 3 and does less inlining, so it isn't for free. We haven't had any performance issue other than with configuration changes though, so I'm willing to give it a go. Presumably the optimisation differences can also be overridden if we need to anyway.

**Comment by amues** [comment]
The changes look good.

**Pull request merged**
