### PR TITLE
Fix crash by returning default values if no alarm field present.

### PR DESCRIPTION
**Pull request by SkyToGround**
### Issue

*DM-1855

### Note

I could see no unit tests for explicitly testing this part of the code base so I did not care to write my own either.

### CODE REVIEW

**Comment by matthew-d-jones** [comment]
I'll add a unit test.

**Comment by matthew-d-jones** [comment]
Added unit tests and improved the test file name to increase the odds of someone finding it in future.

**Comment by mchorazak** [comment]
# [Codecov](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/325?src=pr&el=h1) Report
> Merging [#325](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/325?src=pr&el=desc) into [master](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/commit/782c1ea182996c29e0fc1fb5abf674b956cc262a&el=desc) will **increase** coverage by `0.14%`.
> The diff coverage is `n/a`.


```diff
@@            Coverage Diff             @@
##           master     #325      +/-   ##
==========================================
+ Coverage   70.52%   70.66%   +0.14%     
==========================================
  Files          98       98              
  Lines        2819     2840      +21     
==========================================
+ Hits         1988     2007      +19     
- Misses        831      833       +2     
```

| [Impacted Files](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/325?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [...cs-to-kafka/src/EpicsClient/EpicsClientMonitor.cpp](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/325/diff?src=pr&el=tree#diff-Zm9yd2FyZC1lcGljcy10by1rYWZrYS9zcmMvRXBpY3NDbGllbnQvRXBpY3NDbGllbnRNb25pdG9yLmNwcA==) | `42.30% <0.00%> (-1.12%)` | :arrow_down: |
| [...s-to-kafka/src/tests/f142DataFromPVStructTests.cpp](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/325/diff?src=pr&el=tree#diff-Zm9yd2FyZC1lcGljcy10by1rYWZrYS9zcmMvdGVzdHMvZjE0MkRhdGFGcm9tUFZTdHJ1Y3RUZXN0cy5jcHA=) | | |
| [...-epics-to-kafka/src/tests/GetAlarmDetailsTests.cpp](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/325/diff?src=pr&el=tree#diff-Zm9yd2FyZC1lcGljcy10by1rYWZrYS9zcmMvdGVzdHMvR2V0QWxhcm1EZXRhaWxzVGVzdHMuY3Bw) | `100.00% <0.00%> (ø)` | |
| [...ics-to-kafka/src/schemas/f142/DataFromPVStruct.cpp](https://codecov.io/gh/ess-dmsc/forward-epics-to-kafka/pull/325/diff?src=pr&el=tree#diff-Zm9yd2FyZC1lcGljcy10by1rYWZrYS9zcmMvc2NoZW1hcy9mMTQyL0RhdGFGcm9tUFZTdHJ1Y3QuY3Bw) | `96.55% <0.00%> (+0.55%)` | :arrow_up: |

**Comment by SkyToGround** [comment]
Looks good to me.

**Pull request merged**
