### PR TITLE
Add CMake options to release build

### PR DESCRIPTION
**Pull request by amues**
These flags are required for the application to find its dependencies as
provided in the archived artefact, without setting LD_LIBRARY_PATH.

### Issue

n/a

### Description of work

See text above.

### Nominate for Group Code Review

- [ ] Nominate for code review

### CODE REVIEW

**Comment by matthew-d-jones** [comment]
I'm very confused by this. I cannot get this to work on my machine using `CMAKE_INSTALL_RPATH`, however if I explicitly set the rpath linker flag then it works:
```
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath=$ORIGIN/../lib -Wl,--disable-new-dtags")
```
I think we should definitely set `-Wl,--disable-new-dtags` because this seems to be required when using gcc 7 or higher, so as soon as we move to using devtoolset-7 or 8 on CentOS it will break without it.

The next thing that confused me is the following lines in the top level CMakeLists file:
```
if(CMAKE_BUILD_TYPE MATCHES "Release")
  set(OUTPUT_DIRS "")
else()
  set(OUTPUT_DIRS "NO_OUTPUT_DIRS")
endif()
```
Apparently you added these Afonso, do you remember why?
They are causing the main executable to end up in a different location in debug builds to release builds, so the rpath settings only work for the release build.

**Comment by amues** [comment]
What does `-Wl,--disable-new-dtags` do?

I believe I added the `OUTPUT_DIRS` variable definition so the debug build could still run the tests without any changes in the Jenkinsfile, while the release build (which is what we usually deploy with Ansible) could be run without setting `LD_LIBRARY_PATH` or sourcing _activate_run.sh_. Maybe we should standardise this for all builds; I wouldn't mind having debug builds without `OUTPUT_DIRS`.

**Comment by matthew-d-jones** [comment]
@amues It stops the linker from overriding the dynamic tag in the dynamic table of the ELF image. If I understand correctly, the problem is that the linker in gcc 7 and newer otherwise overrides `DT_RPATH` with the newer `DT_RUNPATH` tag. This stops our RPATH manipulation from actually being used.

I suggest we merge this PR because it works fine for the particular platform and build type that it was intended to fix. I'll then create a new PR with the changes I described above, and let's investigate if that works for all platforms. In particular I would need someone to test it on Mac. Does that sound reasonable @amues @mattclarke ?

**Comment by amues** [comment]
That sounds fine to me. I can help with testing on macOS.

**Pull request merged**
